# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    - env: TOX_ENV=py35
      python: 3.5
    - env: TOX_ENV=py36
      python: 3.6
    - env: TOX_ENV=py37
      python: 3.7
    - env: TOX_ENV=py38
      python: 3.8

script: tox -e $TOX_ENV

install:
    - pip install tox
